Repository Blood-Asp/GT5-Unofficial, pull requests merged in 2018-02, with the labels that each got.

#1303 Bugfix: Small boiler ash types mixing
  src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Bronze.java
  src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Steel.java
Labels: enhancement

#1307 Electrolysis of Sulfur Dioxide/Carbon Dioxide
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
Labels: Bug Fix, In progress, Minor Bug

#1319 Fixed Mufflers and Large Boiler Fuels.
  src/main/java/gregtech/GT_Mod.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_Muffler.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_Bronze.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_Steel.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_Titanium.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_TungstenSteel.java
Labels: Bug Fix, In progress, Minor Bug, enhancement

#1342 Rework gasoline
  src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
Labels: Bug Fix, In progress, Minor Bug, enhancement

#1343 Change Diesel to Combustion
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_DieselEngine.java
  src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
Labels: enhancement

#1345 [unstable branch] Converted to PNG as it should be.
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_BRONZEPREIN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_IRREIN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_TSREIN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_1.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_10.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_11.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_12.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_2.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_3.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_4.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_5.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_6.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_7.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_8.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONII_9.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_1.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_10.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_11.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_12.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_2.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_3.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_4.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_5.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_6.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_7.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_8.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FUSIONI_9.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_DRAGONEGG.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_FUSION.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_FUSION_2.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_FUSION_COIL.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_FUSION_GLASS.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_FUSION_GLASS_YELLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_MAGIC.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_MAGIC_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_MAGIC_FRONT.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_MAGIC_FRONT_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_TELEPORTER.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_TELEPORTER_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/VENT_ADVANCED.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/VENT_NORMAL.png
Labels: duplicate, enhancement

#1304 Magneticraft & FMP Dependency
  src/main/java/gregtech/api/util/GT_ModHandler.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingCrushedOre.java
Labels: Minor Bug, enhancement

#1398 Gasoline revision
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
Labels: enhancement
