Repository Blood-Asp/GT5-Unofficial, pull requests merged in 2018-04, with the labels that each got.

#1436 FEATURE - Added Extruder recipe for Small Gear
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingShaping.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/374.png
Labels: enhancement

#1435 FIX - Updated Frequency Transmitter Recipe
  src/main/java/gregtech/loaders/oreprocessing/ProcessingCrafting.java
Labels: enhancement

#1430 Up cast total EU to long
  src/main/java/gregtech/nei/GT_NEI_AssLineHandler.java
  src/main/java/gregtech/nei/GT_NEI_DefaultHandler.java
Labels: enhancement

#1413 Fixed #1406
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
Labels: Bug Fix, Serious bug

#1410 Oil Drilling Rig fixes
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilDrillBase.java
Labels: Bug Fix, Minor Bug

#1401 Fix Electrolysis of SO2/CO2
  src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
Labels: Bug Fix, Minor Bug

#1316 Small lava boiler "calcification" mechanic
  src/main/java/gregtech/GT_Mod.java
  src/main/java/gregtech/common/GT_Proxy.java
  src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Lava.java
Labels: enhancement
