Repository Blood-Asp/GT5-Unofficial, pull requests merged in 2019-04, with the labels that each got.

#1495 Pipe/cable overhaul; Fluidfilter fix, GC Energy Compat & Misc fixes
  build.gradle
  build.properties
  src/main/java/gregtech/GT_Mod.java
  src/main/java/gregtech/api/GregTech_API.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntityCable.java
  src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Item.java
  src/main/java/gregtech/api/util/GT_Utility.java
  src/main/java/gregtech/common/GT_Proxy.java
  src/main/java/gregtech/common/blocks/GT_Block_Machines.java
  src/main/java/gregtech/common/blocks/GT_Item_Machines.java
  src/main/java/gregtech/common/covers/GT_Cover_Fluidfilter.java
Labels: Bug Fix, In progress, enhancement, info needed

#1527 Improved LuV+conveyor modules
  src/main/java/gregtech/api/util/GT_Utility.java
  src/main/java/gregtech/common/covers/GT_Cover_Conveyor.java
  src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
Labels: enhancement

#1530 Added organic replicator
  src/main/java/gregtech/GT_Mod.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/util/GT_Recipe.java
  src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_OrganicReplicator.java
  src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_BOTTOM.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_BOTTOM_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_FRONT.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_FRONT_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_FRONT_ACTIVE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_SIDE.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_SIDE_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_TOP.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_TOP_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/basicmachines/organic_replicator/OVERLAY_TOP_ACTIVE.png.mcmeta
Labels: Idea, In progress

#1528 Added an Advanced Processing Array
  src/main/java/gregtech/api/GregTech_API.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/blocks/GT_Block_Casings8.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AdvancedProcessingArray.java
  src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
  src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_ROBUST_HSSG.png
  src/main/resources/assets/gregtech/textures/gui/multimachines/AdvancedProcessingArray.png
Labels: In progress
